include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    avoid_print: true

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
